name: worker test
on:
  push:
    branches:
      - master
jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container: golang:1.14.6
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: test
        run: |
          go test ./...
          
      - name: test race
        run: |
          go test ./... -race=1

        