name: worker test
permissions:
  contents: read
on:
  push:
    branches:
      - master
      - develop
      - feature/*
jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container: golang:1.26.2
    steps:

      - name: Check out code
        uses: actions/checkout@v6
        with:
          # avoid requiring a newer self-hosted runner for container auth
          persist-credentials: false

      - name: test
        run: |
          go test ./...
          
      - name: test race
        run: |
          go test ./... -race=1

        